apiVersion: v2
appVersion: "0.16.0"
description: NVR With Realtime Object Detection for IP Cameras
name: frigate
version: 7.11.0
keywords:
  - tensorflow
  - coral
  - ml
home: https://github.com/shyzus/frigate-helm-chart/tree/master/charts/frigate
icon: https://github.com/blakeblackshear/frigate/blob/master/docs/static/img/frigate.png
sources:
  - https://github.com/blakeblackshear/frigate
maintainers:
  - name: blakeblackshear
    email: blakeb@blakeshome.com
  - name: billimek
    email: jeff@billimek.com
